{application,twitterclient,
             [{applications,[kernel,stdlib,elixir,logger]},
              {description,"twitterclient"},
              {modules,['Elixir.FollowService','Elixir.LiveConnection',
                        'Elixir.ReTweetService','Elixir.TweetService',
                        'Elixir.Twitterclient','Elixir.UserService']},
              {registered,[]},
              {vsn,"0.1.0"},
              {extra_applications,[logger]}]}.
